apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 8080
  selector:
    app: backend
    tier: api
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.mesh.kuly.cloud
    secretName: backend-tls
  rules:
    - host: api.mesh.kuly.cloud
      http:
        paths:
        - backend:
            serviceName: backend
            servicePort: 8080
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      imagePullSecrets: 
      - name: gh-pull-secret
      containers:
      - image: {{ .Values.backendImage }}
        name: backend
        ports:
        - containerPort: 8080
          name: backend
---
