name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set image name
      run: echo "IMAGE=ghcr.io/mobil-mit-stil/backend:$(date +%s)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io/mobil-mit-stil
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE }}
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade backend ./helm/ --install --wait --atomic --set=backendImage=${{ env.IMAGE }}
        kubeconfig: '${{ secrets.KUBECONFIG }}'
      
